// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_171717 from "./routes/171717.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $ai from "./routes/ai.tsx";
import * as $aiok from "./routes/aiok.tsx";
import * as $api_activate from "./routes/api/activate.ts";
import * as $api_themes from "./routes/api/themes.ts";
import * as $card from "./routes/card.tsx";
import * as $card_version from "./routes/card_version.tsx";
import * as $custom from "./routes/custom.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $member from "./routes/member.tsx";
import * as $offline from "./routes/offline.tsx";
import * as $position from "./routes/position.tsx";
import * as $positions from "./routes/positions.tsx";
import * as $unopen from "./routes/unopen.tsx";
import * as $animated_counter from "./islands/animated-counter.tsx";
import * as $card_game from "./islands/card-game.tsx";
import * as $error_controls from "./islands/error-controls.tsx";
import * as $offline_reload from "./islands/offline-reload.tsx";
import * as $position_card from "./islands/position-card.tsx";
import * as $position_list from "./islands/position-list.tsx";
import * as $pwa_install from "./islands/pwa-install.tsx";
import * as $theme_switcher from "./islands/theme-switcher.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/171717.tsx": $_171717,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/ai.tsx": $ai,
    "./routes/aiok.tsx": $aiok,
    "./routes/api/activate.ts": $api_activate,
    "./routes/api/themes.ts": $api_themes,
    "./routes/card.tsx": $card,
    "./routes/card_version.tsx": $card_version,
    "./routes/custom.tsx": $custom,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/member.tsx": $member,
    "./routes/offline.tsx": $offline,
    "./routes/position.tsx": $position,
    "./routes/positions.tsx": $positions,
    "./routes/unopen.tsx": $unopen,
  },
  islands: {
    "./islands/animated-counter.tsx": $animated_counter,
    "./islands/card-game.tsx": $card_game,
    "./islands/error-controls.tsx": $error_controls,
    "./islands/offline-reload.tsx": $offline_reload,
    "./islands/position-card.tsx": $position_card,
    "./islands/position-list.tsx": $position_list,
    "./islands/pwa-install.tsx": $pwa_install,
    "./islands/theme-switcher.tsx": $theme_switcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
